
import { PropertyFormValues } from '@/interfaces/propertyFormValues';

export const propertyExtraFields: Array<{ key: keyof PropertyFormValues; label: string; value: any }> = [
  { key: 'country', label: 'Land', value: undefined },

  { key: 'is_new', label: 'Neu', value: undefined },
  { key: 'usable_area_m2', label: 'Nutzfläche (m²)', value: undefined },
  { key: 'plot_area_m2', label: 'Grundstücksfläche (m²)', value: undefined },
  { key: 'rooms', label: 'Räume', value: undefined },
  { key: 'floor', label: 'Etage', value: undefined },
  { key: 'floors_total', label: 'Gesamtanzahl Etagen', value: undefined },
  { key: 'has_elevator', label: 'Aufzug', value: undefined },
  { key: 'parking_spaces', label: 'Parkplätze', value: undefined },
  { key: 'garage', label: 'Garage', value: undefined },
  { key: 'storage_room', label: 'Abstellraum', value: undefined },
  { key: 'kitchen_type', label: 'Küchentyp', value: undefined },
  { key: 'balcony', label: 'Balkon', value: undefined },
  { key: 'terrace', label: 'Terrasse', value: undefined },
  { key: 'build_year', label: 'Baujahr', value: undefined },
  { key: 'garden', label: 'Garten', value: undefined },
  { key: 'pool', label: 'Pool', value: undefined },
  { key: 'fireplace', label: 'Kamin', value: undefined },
  { key: 'sea_view', label: 'Meerblick', value: undefined },
  { key: 'mountain_view', label: 'Bergblick', value: undefined },
  { key: 'city_view', label: 'Stadtblick', value: undefined },
  { key: 'solar_panels', label: 'Solaranlage', value: undefined },
  { key: 'floor_heating', label: 'Fußbodenheizung', value: undefined },
  { key: 'heating', label: 'Heizung', value: undefined },
  { key: 'air_conditioning', label: 'Klimaanlage', value: undefined },
  { key: 'furnished', label: 'Möbliert', value: undefined },
  { key: 'renovation_year', label: 'Renovierungsjahr', value: undefined },
  { key: 'available_from', label: 'Verfügbar ab', value: undefined },
  { key: 'currency', label: 'Währung', value: undefined },
  { key: 'built_area_m2', label: 'Gebäudefläche (m²)', value: undefined },
  { key: 'community_fees', label: 'Gemeinschaftskosten', value: undefined },
  { key: 'deposit', label: 'Kaution', value: undefined },
  { key: 'commission_info', label: 'Provision Info', value: undefined },
  { key: 'energy_label', label: 'Energieklasse', value: undefined },
  { key: 'energy_consumption_kwh_m2y', label: 'Energieverbrauch (kWh/m²/Jahr)', value: undefined },
  { key: 'concierge', label: 'Concierge', value: undefined },
  { key: 'description', label: 'Beschreibung', value: undefined },
  { key: 'notes_internal', label: 'Interne Notizen', value: undefined },
];
