import { nullable, z } from 'zod';

export const propertyFormSchemaZod = z.object({
  category: z.enum(['haus', 'wohnung', 'gewerbe', 'grundstueck', 'sonstige'], { message: 'Kategorie ist erforderlich' }),
  title: z.string().min(1, { message: 'Titel ist erforderlich' }),
  agent: z.string().min(1, { message: 'Makler ist erforderlich' }),
  owner: z.string().min(1, { message: 'Eigentümer ist erforderlich' }),
  operation: z.enum(['SELL', 'RENT'], { message: 'Vermarktungsart ist erforderlich' }),
  type: z.enum(['haus', 'wohnung', 'gewerbe', 'grundstueck', 'sonstige'], { message: 'Typ ist erforderlich' }),
  status: z.enum(['PUBLISHED', 'RESERVED', 'SOLD', 'RENTED', 'DRAFT', 'HIDDEN'], { message: 'Status ist erforderlich' }),
  address_line: z.string().min(1, { message: 'Adresse ist erforderlich' }),
  city: z.string().min(1, { message: 'Stadt ist erforderlich' }),
  postal_code: z.string().min(1, { message: 'Postleitzahl ist erforderlich' }),
  built_area_m2: z.number().refine(val => val !== undefined && val !== null, { message: 'Wohnfläche ist erforderlich' }),
  rooms: z.number().refine(val => val !== undefined && val !== null, { message: 'Zimmer ist erforderlich' }),
  bedrooms: z.number().refine(val => val !== undefined && val !== null, { message: 'Schlafzimmer ist erforderlich' }),
  bathrooms: z.number().refine(val => val !== undefined && val !== null, { message: 'Badezimmer ist erforderlich' }),
  price_amount: z.number().refine(val => val !== undefined && val !== null, { message: 'Preis ist erforderlich' }),
  currency: z.string().min(1, { message: 'Währung ist erforderlich' }),
  main_image: z.string().url({ message: 'Hauptbild muss eine gültige URL sein' }).min(1, { message: 'Hauptbild ist erforderlich' }),

  // Opcionales
  country: z.string().optional(),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  usable_area_m2: z.number().optional().nullable(),
  plot_area_m2: z.number().optional().nullable(),
  floor: z.number().optional().nullable(),
  floors_total: z.number().optional().nullable(),
  has_elevator: z.boolean().optional(),
  parking_spaces: z.number().optional().nullable(),
  garage: z.boolean().optional(),
  storage_room: z.boolean().optional(),
  kitchen_type: z.string().optional(),
  heating: z.string().optional(),
  air_conditioning: z.boolean().optional(),
  furnished: z.string().optional(),
  build_year: z.number().optional().nullable(),
  renovation_year: z.number().optional().nullable(),
  available_from: z.date().optional().nullable(),
  community_fees: z.number().optional().nullable(),
  deposit: z.number().optional().nullable(),
  commission_info: z.string().optional(),
  energy_label: z.string().optional(),
  energy_consumption_kwh_m2y: z.number().optional().nullable(),
  balcony: z.boolean().optional(),
  terrace: z.boolean().optional(),
  garden: z.boolean().optional(),
  pool: z.boolean().optional(),
  fireplace: z.boolean().optional(),
  sea_view: z.boolean().optional(),
  mountain_view: z.boolean().optional(),
  city_view: z.boolean().optional(),
  solar_panels: z.boolean().optional(),
  floor_heating: z.boolean().optional(),
  concierge: z.boolean().optional(),
  description: z.string().optional(),
  notes_internal: z.string().optional(),
  is_new: z.boolean().optional(),
});
