

import { ReactQueryProvider } from './providers/ReactQueryProvider';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import CompanyTitle from "@/components/ui/companyTitle/CompanyTitle";
import Script from "next/script";
import GlobalBorderColor from "@/components/ui/GlobalBorderColor";

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Rumpke Immobilien",
  description: "Generated by Rumpke Immobilien",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased">
        <Script src="https://widget.cloudinary.com/v2.0/global/all.js" strategy="beforeInteractive" />
        <ThemeProvider>
          <ReactQueryProvider>
            <div className="bg-bg-l text-zinc-800 dark:bg-bg-d dark:text-zinc-100 transition-colors duration-100 ease-out xl:px-6">
              {/* <GlobalBorderColor /> */}
              {children}
            </div>
          </ReactQueryProvider>
          <CompanyTitle />
        </ThemeProvider>
      </body>
    </html>
  );
}
