
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { BorderBars } from "@/components/ui/border-bars/BorderBars";
import CompanyTitle from "@/components/ui/companyTitle/CompanyTitle";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rumpke Immobilien",
  description: "Generated by Rumpke Immobilien",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <BorderBars />
          <div className="bg-bg-l text-zinc-800 dark:bg-bg-d dark:text-zinc-100  transition-colors duration-100 ease-out xl:px-6">
            {children}
          </div>
          <CompanyTitle/>
          <BorderBars />
        </ThemeProvider>
      </body>
    </html>
  );
}
