
import { ReactQueryProvider } from './providers/ReactQueryProvider';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import CompanyTitle from "@/components/ui/companyTitle/CompanyTitle";
import Script from "next/script";
import GlobalBorderColor from "@/components/ui/GlobalBorderColor";
import ContactButtom from '@/components/ui/contact-buttom/ContactTooltip';
import Topmenu from '@/components/ui/top-menu/TopMenu';
import { Title } from '@/components/ui/title/Title';
import Sidebar from '@/components/ui/sidebar/Sidebar';
import SidebarDesktop from '@/components/ui/sidebar/SidebarDesktop';
import Footer from '@/components/ui/footer/Footer';

const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Rumpke Immobilien",
  description: "Generated by Rumpke Immobilien",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={inter.className}>
      <body className="antialiased">
        <Script src="https://widget.cloudinary.com/v2.0/global/all.js" strategy="beforeInteractive" />
        <ThemeProvider>
          <ReactQueryProvider>
            <div className="bg-bg-l text-zinc-800 dark:bg-bg-d dark:text-zinc-100 transition-colors duration-100 ease-out">
              <div className='hidden md:block fixed top-0 right-6 xl:right-36 z-500'>
                <ContactButtom />
              </div>
              <GlobalBorderColor />
              <Topmenu />
              <Title
                title="Rumpke Immobilien"
                subtitle="Finde deine Traumimmobilie"
                className='flex-1 md:hidden mb-4 ml-2 text-primary'
              />
              <div className="flex">
                <div className=" mx-auto">
                  {children}
                </div>
              </div>
              <Footer />
            </div>
          </ReactQueryProvider>
          <CompanyTitle />
        </ThemeProvider>
      </body>
    </html>
  );
}
