import { Agent } from '@/interfaces/agent-interface';

export const agentsSeed: Agent[] = [
  {
    id: '1',
    first_name: 'Ann-Christin',
    last_name: 'Rumpke',
    email: 'ann-christin.rumpke@rumpke-immobilien.de',
    phone: '+49 123 456 7890',
    mobile: '+49 170 123 4567',
    languages: ['Deutsch', 'English', 'Español'],
    photo_url: '/imgs/ann-christin.png',
    position_de: 'Geschäftsführerin & Immobilienmaklerin',
    position_en: 'CEO & Real Estate Agent',
    position_es: 'Directora General & Agente Inmobiliaria',
    bio_de: 'Mit über 15 Jahren Erfahrung im Immobilienmarkt begleite ich Sie professionell bei Ihrem Immobilienkauf oder -verkauf. Meine Leidenschaft ist es, für jeden Kunden die perfekte Immobilie zu finden und den gesamten Prozess so reibungslos wie möglich zu gestalten.',
    bio_en: 'With over 15 years of experience in the real estate market, I professionally guide you through your property purchase or sale. My passion is finding the perfect property for every client and making the entire process as smooth as possible.',
    bio_es: 'Con más de 15 años de experiencia en el mercado inmobiliario, te acompaño profesionalmente en la compra o venta de tu propiedad. Mi pasión es encontrar la propiedad perfecta para cada cliente y hacer que todo el proceso sea lo más fluido posible.',
    is_public: true,
    is_active: true,
  },
  {
    id: '2',
    first_name: 'Maximilian',
    last_name: 'Schmidt',
    email: 'max.schmidt@rumpke-immobilien.de',
    phone: '+49 123 456 7891',
    mobile: '+49 170 123 4568',
    languages: ['Deutsch', 'English'],
    photo_url: '/imgs/ann-christin.png', // Placeholder
    position_de: 'Senior Immobilienberater',
    position_en: 'Senior Real Estate Consultant',
    position_es: 'Consultor Inmobiliario Senior',
    bio_de: 'Als erfahrener Immobilienberater unterstütze ich Sie bei der Suche nach Ihrer Traumimmobilie. Mein Fokus liegt auf individuelle Beratung und maßgeschneiderte Lösungen für jeden Kunden.',
    bio_en: 'As an experienced real estate consultant, I support you in finding your dream property. My focus is on individual advice and tailored solutions for every client.',
    bio_es: 'Como consultor inmobiliario experimentado, te apoyo en la búsqueda de tu propiedad soñada. Mi enfoque está en el asesoramiento individual y soluciones a medida para cada cliente.',
    is_public: true,
    is_active: true,
  },
];
