// export interface PropertyFormValues {
//   id?: string;
//   slug: string;
//   reference_code: string;
//   operation: 'SELL' | 'RENT';
//   type: 'APARTMENT' | 'HOUSE' | 'VILLA' | 'PLOT' | 'DUPLEX' | 'PENTHOUSE' | 'STUDIO' | 'OFFICE';
//   is_featured?: boolean;
//   is_new?: boolean;
//   address_line: string;
//   city: string;
//   postal_code: string;
//   region: string;
//   country?: string;
//   latitude?: number;
//   longitude?: number;
//   built_area_m2: number;
//   usable_area_m2?: number;
//   plot_area_m2?: number;
//   rooms: number;
//   bedrooms: number;
//   bathrooms: number;
//   floor?: number;
//   floors_total?: number;
//   has_elevator?: boolean;
//   parking_spaces?: number;
//   garage?: boolean;
//   storage_room?: boolean;
//   kitchen_type?: string;
//   heating?: string;
//   air_conditioning?: boolean;
//   furnished?: string;
//   orientation?: string;
//   build_year?: number;
//   renovation_year?: number;
//   status: 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'RENTED' | 'DRAFT' | 'HIDDEN';
//   available_from?: Date | string;
//   price_amount: number;
//   currency?: string;
//   price_frequency?: string;
//   community_fees?: number;
//   property_tax?: number;
//   deposit?: number;
//   commission_info?: string;
//   energy_label?: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
//   energy_consumption_kwh_m2y?: number;
//   co2_emissions_kg_m2y?: number;
//   energy_certificate_url?: string;
//   balcony?: boolean;
//   terrace?: boolean;
//   garden?: boolean;
//   pool?: boolean;
//   fireplace?: boolean;
//   pets_allowed?: boolean;
//   sea_view?: boolean;
//   mountain_view?: boolean;
//   city_view?: boolean;
//   double_glazing?: boolean;
//   smart_home?: boolean;
//   solar_panels?: boolean;
//   floor_heating?: boolean;
//   security_door?: boolean;
//   cctv?: boolean;
//   concierge?: boolean;
//   seo_title?: string;
//   seo_description?: string;
//   description?: string;
//   notes_internal?: string;
//   published_at?: Date | string;
//   archived_at?: Date | string;
//   agent_id?: string;
//   categories?: string[];
//   amenities?: string[];
//   tags?: string[];
//   media?: string[];
// }


export interface PropertyFormValues {
  agent: string;
  operation: 'SELL' | 'RENT';
  type: 'APARTMENT' | 'HOUSE' | 'VILLA' | 'PLOT' | 'DUPLEX' | 'PENTHOUSE' | 'STUDIO' | 'OFFICE';
  city: string;
  postal_code: string;
  built_area_m2: number;
  rooms: number;
  bedrooms: number;
  bathrooms: number;
  price_amount: number;
  // ???
  status?: 'PUBLISHED' | 'RESERVED' | 'SOLD' | 'RENTED' | 'DRAFT' | 'HIDDEN';
  address_line?: string;
  country?: string;
  latitude?: number;
  longitude?: number;
  usable_area_m2?: number;
  plot_area_m2?: number;
  floor?: number;
  floors_total?: number;
  has_elevator?: boolean;
  parking_spaces?: number;
  garage?: boolean;
  storage_room?: boolean;
  kitchen_type?: string;
  heating?: string;
  air_conditioning?: boolean;
  furnished?: string;
  build_year?: number;
  renovation_year?: number;
  available_from?: Date | string;
  currency?: string;
  community_fees?: number;
  deposit?: number;
  commission_info?: string;
  energy_label?: 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G';
  energy_consumption_kwh_m2y?: number;
  balcony?: boolean;
  terrace?: boolean;
  garden?: boolean;
  pool?: boolean;
  fireplace?: boolean;
  sea_view?: boolean;
  mountain_view?: boolean;
  city_view?: boolean;
  solar_panels?: boolean;
  floor_heating?: boolean;
  concierge?: boolean;
  description?: string;
  notes_internal?: string;
  title?: string;
  is_new?: boolean;

}
